app:
  name: ui
  image:
    repository: 'onecx<% if(standalone){ %>-standalone<% } %>/<%= fileName %>'
  routing:
    enabled: true
    path: /mfe/<%= propertyName %>/
<% if(!standalone){ %>  
  operator:
    # Microfrontend
    microfrontend:
      enabled: true
      specs:
        main:
          exposedModule: './<%= remoteModuleName %>Module'        
          description: 'OneCX <%= remoteModuleName %> Module'
          note: 'OneCX <%= remoteModuleName %> UI module auto import via MF operator'
          type: MODULE
          technology: WEBCOMPONENTMODULE
          remoteName: <%= remoteModuleFileName %>
          tagName: <%= remoteModuleFileName %>-webcomponent
    # Permission
    # ACTION S11 Update permissions and roles: https://onecx.github.io/docs/nx-plugins/current/general/getting_started/search/updatePermissions.html#_action_s11_update_permissions_and_roles
    permission:
      enabled: true
      spec:
        permissions:
    # Keycloak
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: "<%= fileName %>"

# PIPE Config
<% } %>